<a href="https://colab.research.google.com/github/Hash-sd/Data-Mining/blob/main/Principal%20Component%20Analysis%20(PCA).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import library yang akan digunakan
import numpy as np

In [ ]:
# import data yang akan di reduksi menggunakan numpy
data = np.array([
    [2.5, 2.4, 3.5, 3.6], [0.5, 0.7, 1.2, 1.3],
    [2.2, 2.9, 3.0, 3.4],
    [1.9, 2.2, 2.5, 2.7],
    [3.1, 3.6, 4.1, 4.0],
    [2.3, 2.7, 3.1, 3.0],
    [2.0, 1.6, 2.3, 2.4],
    [1.0, 1.1, 1.5, 1.6],
    [1.5, 1.6, 2.0, 2.1],
    [1.1, 0.9, 1.3, 1.4]
])
#standarisasi data
mean=np.mean(data,axis=0)
std_dev = np.std(data, axis=0)
Z= (data - mean) / std_dev
print(Z)


[[ 0.92627881  0.47833912  1.13455516  1.16201358]
 [-1.7585873  -1.41276904 -1.35066091 -1.3833495 ]
 [ 0.52354889  1.0345474   0.5942908   0.94067766]
 [ 0.12081898  0.25585581  0.05402644  0.16600194]
 [ 1.73173864  1.813239    1.78287239  1.60468542]
 [ 0.6577922   0.81206409  0.70234367  0.49800582]
 [ 0.25506228 -0.41159413 -0.16207931 -0.16600194]
 [-1.08737078 -0.96780241 -1.02650229 -1.05134562]
 [-0.41615425 -0.41159413 -0.48623793 -0.49800582]
 [-0.95312747 -1.19028572 -1.24260803 -1.27268154]]


In [ ]:
#hitung matriks covarian dari Z
cov_matrix = np.cov(Z, rowvar=False)

In [ ]:
#Hitung nilai eigen dan vektor eigen dari matriks covarian
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

In [ ]:
#hitung proporsi variansi dari nilai eigen
total_variance = np.sum(eigenvalues)
explained_variance_ratio = eigenvalues / total_variance

In [ ]:
#hitung kontribusi variansi dari nilai eigen
cumulative_variance_ratio = np.cumsum(explained_variance_ratio)

print("eigen val",eigenvalues)
print("proporsi", explained_variance_ratio)
print("kumulatif",cumulative_variance_ratio)

eigen val [4.33318943 0.06538576 0.0358081  0.01006116]
proporsi [0.97496762 0.0147118  0.00805682 0.00226376]
kumulatif [0.97496762 0.98967942 0.99773624 1.        ]


In [ ]:
#tentukan ambang batas dalam pemilihan nilai eigen
threshold = 0.9
n_components = np.argmax(cumulative_variance_ratio >= threshold) + 1
print("Jumlah komponen yang diperlukan:", n_components)

Jumlah komponen yang diperlukan: 1


In [ ]:
#urutkan nilai dan vektor eigen
sorted_indices = np.argsort(eigenvalues)[::-1]
sorted_eigenvalues = eigenvalues[sorted_indices]
sorted_eigenvectors = eigenvectors[:, sorted_indices]

In [ ]:
#ambil komponen utama sesuai n_componen
n_components = 1
W = sorted_eigenvectors[:, :n_components]

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(data)

In [ ]:
#transformasi data
Y = Z @ W
Y

array([[-1.85364122],
       [ 2.95159575],
       [-1.54579331],
       [-0.29769242],
       [-3.46574526],
       [-1.33423136],
       [ 0.24222221],
       [ 2.066633  ],
       [ 0.90644968],
       [ 2.33020293]])

### Sklearn

In [ ]:
#Standarisasi data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(data)

In [ ]:
#reduksi dimensi menggunakan PCA
#dipilih satu komponen sesuai n_componen pada bg.1
from sklearn.decomposition import PCA
pca = PCA(n_components=1)
X_pca = pca.fit_transform(X_scaled)

In [ ]:
X_pca

array([[ 1.85364122],
       [-2.95159575],
       [ 1.54579331],
       [ 0.29769242],
       [ 3.46574526],
       [ 1.33423136],
       [-0.24222221],
       [-2.066633  ],
       [-0.90644968],
       [-2.33020293]])